第5回課題の提出
takayukinagashima/RaiseTech pull request #6
Opened 2024-07-13 12:13 UTC by takayukinagashima

お世話になっております。 第5回課題の提出をさせていただきます。
恐れ入りますが、ご確認のほどよろしくお願いいたします！

2024-07-13 13:50 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-07-13 13:50 UTC, MasatoshiMizumoto commented on task-image/lecture05/lecture05_diagram_ver3.png
Internetのアイコンがデザイン違っていそうなので確認お願いします！
EC2も違うかもです！（複数系かどうかでアイコン異なるサービスもあります）

2024-07-14 02:09 UTC, takayukinagashima commented on task-image/lecture05/lecture05_diagram_ver3.png
ご確認ありがとうございます！
Internetのアイコンの用途を確認し、正しいと思われるものと差し替えて、修正した構成図をmdファイルに追加しました。
またEC2インスタンスは一つだけの環境で構築しているので、こちらもアイコンを差し替えて修正しています。(修正前は見栄え、統一感だけを意識していました…)
お手数ですが、今一度ご確認のほどお願いいたします！

2024-07-14 02:43 UTC, MasatoshiMizumoto approved these changes
LGTMです！
修正前のものは消してしまって大丈夫です！

2024-07-14 03:00 UTC, takayukinagashima commented
修正前の構成図を消したmdファイルをpushしました！

2024-07-14 03:27 UTC, merged